[package]
name = "jemalloc_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
jemalloc-sys = {version="=0.5.4",features=["disable_initial_exec_tls"] }

[lib]
name = "jemalloc_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]

